weights: .\runs\train\exp19\weights\last.pt
cfg: ''
data: D:\DL-ML-DRL\CV\yolo-series\yolov5-yolo412\yolov5_facenet\data\safe_data.yaml
hyp: data\hyps\hyp.scratch.yaml
epochs: 100
batch_size: 4
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: true
single_cls: false
adam: false
sync_bn: false
workers: 0
project: runs\train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp19
